### ISSUE TITLE
Expandable options on Ask/Offer form

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#310]
After checking a Category (and SubCategory?) on Ask/Offer form, person would see metadata options

**Ask:**
- urgency_level_id
- recurring (on/off)
- requested_by_date (new field on listing)
- title
- description

**Offer:**
- monthly_matches_max (field is currently on person, needs to move to be on listing)
- monthly_donation_amount_max (field is currently on person, needs to move to be on listing)
- title
- description

Note: of these, description is the highest priority.

Update: the exact fields specified here might be out of date -- please discuss with maintainers before diving in.

**Comment by h-m-m** [comment]
If it's okay with everyone, I'm going to take the `?` items, and fold them out into a "needs discussion" ticket so that people feel clear to implement the other items in the list
