### ISSUE TITLE
Implement combined form (Asks & Offers)

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#315]
Some of our mutual aid orgs would prefer to allow users to fill out both asks and offers on the same form. This is to counter the common narrative/assumption that values people who 'give' and de-values those who 'take'. Allowing a user to do both on the same page is intended to signal that we all give and take at different moments and could be considered more aligned with mutual-aid values.

We'll need some UX design to meet this intention while also remaining clear/straightforward for someone who only wants to fill in one or the other.

**Comment by svileshina** [comment]
Is this a user that can create and ask and offer at the same time? Need a wireframe or some other clarification

**Comment by exbinary** [comment]
Added a description @svileshina.
