### ISSUE TITLE
Add rubocop

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#34]

**Comment by metamoni** [comment]
I'd like to work on this. Is fixing the issues that pop up after installing part of this? Because I'd be happy to fix them as part of the same PR.

**Comment by smoline** [comment]
@maebeale I am happy to work on this one!

**Comment by smoline** [comment]
Should I fix some of the issues in this PR, or would you also like a few PRs fixing some of the 3000 issues rubocop is reporting? How would you like me to break them up to make the PRs less merge conflict messy?

**Comment by h-m-m** [comment]
Hi, @smoline! I'm so happy you're taking on this task.

I'm definitely interested in @maebeale's take on this. That said, maybe you could split those up into two PRs? It might be nice to have one PR that's Rubocop with existing issues put in the todo file or something like that, and a second PR that fixes some of the more straight-forward issues. That way we can still get some fixes in place, but a problem with any of the fixes won't hold up your PR for Rubocop itself. What do you think?

**Comment by smoline** [comment]
Sounds great!

**Comment by maebeale** [comment]
Love that suggestion, @h-m-m ! @smoline so nice to have you on this project!!!
