### ISSUE TITLE
User is able to get to Edit account from nav

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#365]

**Comment by armahillo** [comment]
Assuming we're not doing anything weird with devise, this is normally straighforward. I've not done much with Vue and haven't reviewed the app enough to know, but if it's the standard approach I'll put up a PR and retroactively self-assign

**Comment by maebeale** [comment]
AWESOME! Yeah, you can ignore the vue stuff. Totally straight devise.
Changing password is SO helpful!!!

(We also can't currently create Users bc of a devise reroute.)

**Comment by armahillo** [comment]
Is there an existing "profile" page for users to manage their own profile? 

I can get to `http://localhost:3000/users/edit?locale=en` via the Admin area

**Comment by maebeale** [comment]
Yeah, I took it out of the nav bc we have so many things. Was going to make
a dropdown under Logout to include it there, but don't know vue well enough
yet to pull that off. Figured if needed, for now, ppl could go to the Users
index and click edit button.

**Comment by armahillo** [comment]
So it appears this feature already exists, it just needs to be linked somewhere.

I think this issue should probably be re-written to be "Add link to header for /users/edit"? There will need to be authorization set up for this action, eventually, so that people don't URL inject other user's edit pages, something like:

```ruby
def edit
    if @user == current_user || !current_user.is_admin?
      redirect_to edit_user_registration_path
    else
      set_form_dropdowns
    end
  end
```

**Comment by armahillo** [comment]
Just confirmed I can change my password via `/users/edit` -- so really we just need a link added to the nav, and (eventually) access-control set

**Comment by maebeale** [comment]
Wuttt???? Um, ok then!

**Comment by maebeale** [comment]
Is the change my password button working when not logged in? Maybe it was meant about that?

**Comment by armahillo** [comment]
I just verified:
> As a signed-out user, when I attempt to access /users/edit and /users/1/edit, I am sent to a sign-in page

We should probably create some system specs for this stuff.

**Comment by maebeale** [comment]
YESSSS

**Comment by armahillo** [comment]
I dont see any system specs right now and that requires enough configuration change I think it should probably be its own issue

**Comment by h-m-m** [comment]
Is there any of this that is dependent on getting Pundit deployed first?

**Comment by exbinary** [comment]
No longer an issue.
