### ISSUE TITLE
WhatsApp icon not working on TileBrowser

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#391]

**Comment by leahriffell** [comment]
Hi @maebeale! We (my open source school club) are interested in this issue!

Are you able to assign it to me? We can do a co-authored commit.  Is there any additional context needed before starting?

**Comment by maebeale** [comment]
@leahriffell Fantastic! I don't think there's any more to share, other than that the icon needs to work both on the Vue side (/contributions) AND on the Rails side (/contact_methods).

**Comment by leahriffell** [comment]
Ok thank you @maebeale! We just submitted our[ first PR ](https://github.com/rubyforgood/mutual-aid/pull/804):)
