### ISSUE TITLE
Remove uses of `mobility_text_translations`

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#411]
On postgres, there's no downside to just using `text` so we should be able to use just `text_translations`.

**Comment by maebeale** [comment]
same is true for string, tho. you prefer text to string?

**Comment by exbinary** [comment]
Maybe i'm misunderstanding or miscommunicating :)

I'm assuming some of the translatable strings we want to store could be on the bigger side and so will require a `text` type.

On postgres, there's [no downside](https://www.postgresql.org/docs/current/datatype-character.html) to using `text` over `string`:
> https://www.postgresql.org/docs/current/datatype-character.html

I'm suggesting that we only use `text` types for any translatable fields. That way, we can accommodate any length of string and also only ever have to join on one mobility table.

**Comment by maebeale** [comment]
Cool. Yeah, we're in agreement about the approach and reasoning, just
differing re which table to use as the single join. In postgres they're the
same (string and text), so defaulted to only using the string translations
table. (Longer length doesn't mean we need text in postgres.) But if you
feel strongly we switch from only string to only text, we can, but we
wouldn't be getting any more help out of postgres, and, we'd be down one
index from mobility.

**Comment by exbinary** [comment]
Oh i see, the difference between the tables are:
1. `character varying` vs. `text`, which you're right is no different.
2. `string_translations` has an extra index. I'm not sure why that's different, but i assume its a Good Thing :)

Knowing this, i'm good with `string_translations`. I can change the issue to reflect this.

**Comment by maebeale** [comment]
Yup, agree!
Cool! :)

I did add the model for text translations just to be able to run the
stats_check, but, prob it'd be ok to remove it and add it to the skipped
tables list in that file.
