### ISSUE TITLE
Add pagination to People index

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#528]

**Comment by yez** [comment]
I'd be interested in addressing this issue, is there an accepted gem/pattern for pagination today you'd like implemented?

**Comment by exbinary** [comment]
Hello @yez! 👋🏾  Appreciate your interest.

We haven't added pagination to any of our pages/endpoints yet, so no accepted gem or pattern is in place.

That said, i've been meaning to give [pagy](https://github.com/ddnexus/pagy) a go.
Open to thoughts on this?

**Comment by yez** [comment]
Pagy looks neat, I'll try it out, thanks!
