### ISSUE TITLE
Add search filter to People index

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#530]

**Comment by yez** [comment]
Hello I'd be interested in tackling this issue. Is there a specific set of fields you'd like to be able to filter the `peoples_controller#index` method by?

**Comment by maebeale** [comment]
hello and thanks for your interest, @yez !

ideally, each column shown on the People index (name, contact preference, email, phone, contact timeframe), and filters are additive (i could search by "maebeale" in the name field and "email" in the contact preference field).

i'll assign you to this issue now. feel free to reach out with more questions!
