### ISSUE TITLE
Add "unmatchable" to Listing

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#559]
LAMA wants Listings to be able to be removed from the Contributions page list. 

Essentially the opposite of inhexhaustible.

Should we add another boolean, or combine it w inexhaustible to be `matchable_status` or something?

Some Listings end up not provided for (not 100% re what the various reasons are), so those are the ones that need to be "hidden/removed from list".

**Comment by svileshina** [comment]
I think this is an ongoing convo
