### ISSUE TITLE
Admin can see who created/updated HelpTickets and when 

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#611]
Add created_by_id and updated_by_id to HelpTicket, and autopopulate these on save

**Comment by stillsheryl** [comment]
@maebeale I'm part of the Turing open-source club and we'd like to claim this one if it's still available!

**Comment by leahriffell** [comment]
Hi @maebeale! (colleague of @stillsheryl's here). We've been looking at this ticket more and am wondering if you can provide some clarification on the following:

- Where on the application are Help Tickets found? I've logged in as an admin but do not see this on the dashboard. Is this feature called something else?
- It looks like HelpTickets is not a table in the database. I see a partial called `_support_tickets.html.erb` but I don't believe this is actually being rendered anywhere? 

Thanks so much!

**Comment by maebeale** [comment]
Good sleuthing, @leahriffell ! You're right that it's not called help ticket in the db -- support ticket is what you want to use. It should show in the navbar while logged in?

**Comment by maebeale** [comment]
(P.S. @leahriffell that index probably should get added to the dashboard, tho! That's a great point. I'll make another ticket for that.)

**Comment by leahriffell** [comment]
Thank you @maebeale! Could this table be called something other than support ticket? We're not seeing anything with `ticket` in the name in the schema.rb file.  Maybe communication_logs or feedback?

**Comment by leahriffell** [comment]
Hi @maebeale! @exbinary and @h-m-m dug into this ticket more with us. 

Is this referring to the input when user submits software_feedback via the Feedback button in nav bar? 

If so:
- there is created_by on that table but no updated_by yet (we can add that)
- should the created by and updated by user be displayed for the admin to view? current screenshot below:
<img width="454" alt="Screen Shot 2021-01-28 at 6 18 20 PM" src="https://user-images.githubusercontent.com/34531014/106222494-d918b680-619c-11eb-8caf-4a906f212e5c.png">
