### ISSUE TITLE
Implement redesigned Vue landing page

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#626]
![Screenshot_20200701-203256](https://user-images.githubusercontent.com/7607813/91501270-45605880-e893-11ea-8e7f-fcdc3b046700.jpg)
![Lama web design 1](https://user-images.githubusercontent.com/7607813/91501272-45f8ef00-e893-11ea-876b-76fcd5f27722.jpg)
![Lama design notes 2](https://user-images.githubusercontent.com/7607813/91501274-485b4900-e893-11ea-8c0e-c6c773683386.jpg)

**Comment by slaloggia** [comment]
Giving this a shot!

**Comment by svileshina** [comment]
Excited for the weekend - let us know if you have any questions!
