### ISSUE TITLE
Design a peer-to-peer flow

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#640]
We'd love to talk with you about this! We could use your help designing and thinking through this feature. 

The app currently does not support a peer-to-peer mode (only dispatch mode).

Once implemented, this feature will:
* Allow a user to initiate a match request on any ask or offer (possibly from the ask/offer page and/or the contributions page).
* Somehow notify the owner of the ask/offer and allow them to accept or decline.
* Allow peers to communicate with each other, ideally w/o exposing private info (but this might be a stretch goal?).
* Somehow be aware of communication between peers so that the system can update ask/offer statuses w/o requiring users to keep them up to date.
* Probably provide a way for users to review any outstanding match requests (see #639).

Other (possibly duplicate) notes and from our meeting):
* Contributions page publicly viewable
* See something when clicking respond button - how would this look?
* Craigslist model?
* How does individual organization fit in?
* Moderation?
* What’s the right balance of hands on/off?
* Messaging: contact person on the other side by email or text (for a later date: Storing history or not?)
• Workflow - asking ppl to leave site for messaging / email?
* Thinking about mobile users
* Be able to report on completion

**Comment by kevinschlabach** [comment]
#709 and #711 are initial story slices to making progress on this feature, this item will likely need to be revised after learning and deploying from those items.

**Comment by thestephenmarshall** [comment]
Here is the initial envisioned P2P flow. Some things to note:

- Contributions page will not require login (future)
- `Dispatch Required` section needs separate flow created for dispatchers

![p2p-flow1](https://user-images.githubusercontent.com/2293844/93891591-2ea1fb80-fcb1-11ea-992c-808f35b57e14.jpg)
