### ISSUE TITLE
User is presented a 'mad libs' style prompt to quickly specify what they're looking for

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#641]
Provide user a dynamic fill-in-the-blank sentence that filters the contributions list. This would likely appear 'above-the-fold' and be an alternative way to filter (from the existing checkboxes).

**Comment by exbinary** [comment]
@h-m-m said in a slack thread:
> Since a couple people asked what we meant by the "mad libs" ticket:
>
> The idea there is that we'd change the search page. Instead of a long list of checkboxes or the like, we'd have a fill-in-the-blanks text at the top and maybe people would appreciate that better, especially for p2p
>
> So, for example a sentence like "I have ______ and would like to ______ in _______"
>
> Where those blank lines bring up dropdowns. The first one could be are "a need for" "the ability to give" with a second dropdown for "cash", "babysitting" etc
>
> And the last dropdown could be "the west side neighborhood" or "lancaster county"

To which i asked:
> would this replace the existing checkbox filters or be an alternative way to achieve the same thing?

And Howard replied:
> I think we'd definitely keep the checkboxes for a dispatcher workflow
> I don't think we've decided on keeping them or not for the peer workflow, though. I'm thinking maybe not, but that's my gut feel and not anyone else's

And @maebeale added:
> i like them there for both, personally, but open to suggestion/feedback

**Comment by exbinary** [comment]
@viamin then said in a slack thread:
> My first pass was to add a search box above the checkboxes and filter the conditions (just on the frontend) but that was my interpretation of “mad-libs”

<img width="507" alt="Screen Shot 2020-09-05 at 1 43 43 PM" src="https://user-images.githubusercontent.com/8330/92313364-08821900-ef99-11ea-9e62-23f9ddfc2575.png">

**Comment by exbinary** [comment]
I like the 'Quick filter' search option as well. I think it solves some of the concerns motivating this issue.

My sense is that we wanted something that was immediately obvious to a user and would be sort of an 'entry point' into this page. The current design requires users grok the whole page and then realize they can thin the list by messing with filters.

We wanted to experiment with something further up the page that stands out and encourages use before the results list is even interacted with.

Am i describing this correctly @h-m-m, @maebeale ?

**Comment by viamin** [comment]
I'll spike out something more mad-libsy.

**Comment by maebeale** [comment]
yes, LOVE the quick filter too! (in addition to a sentence thing in large font at top).

i'll find an original mockup we'd had for this page, bc there was some other searching we'd wanted to do at one point

**Comment by svileshina** [comment]
Excited for the weekend - thanks for taking this on!
