### ISSUE TITLE
[DISCUSSION] Discuss moral/security issues around P2P

### ISSUE THREAD

**Issue by reevesalic** [rubyforgood/mutual-aid#649]
Address issues with moral issues with P2P - what information do groups ask for? How is it available to users?, etc - but do not let it stop developing some type MVP

Outcome of this discussion could be a PR checklist that becomes an app wide standard.

**Comment by grenewode** [comment]
To clarify, I think this is referring mostly to **operational** security issues (eg, what kind of adversarial p2p behaviors do we want to protect against) as opposed to **technical** security issues (eg, properly encrypting user data)
