### ISSUE TITLE
P2P Happy path

### ISSUE THREAD

**Issue by reevesalic** [rubyforgood/mutual-aid#650]
Bare bones “happy path” P2P - cost effective and connect people
Contributions page publically viewable
See something when clicking respond button - how would this look? Craigslist model? How does individual organization fit in? Moderation? What’s the right balance of hands on/off? 
Messaging: contact person on the other side by email or text (for a later date: Storing history or not? Workflow - asking ppl to leave site for messaging / email? Thinking about mobile users)
Be able to report on completion

**Comment by exbinary** [comment]
IIUC, this is the same as #640 -- am moving the details from here into that issue and closing this one.
But pls lmk if i'm missing some difference.
