### ISSUE TITLE
Wireframe for Community Resources page

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#655]
The public will be able to visit Community Resources to see a list of regional organizations and programs that might be of help to them.

http://mutual-aid-app.herokuapp.com/community_resources_list

if you click the "Add community resource" button you'll see the data we'll have available

On this page people will want to search for organizations by category, name/title, mileage (once we add mapping functionality) -- very similar to Contributions Page.

They'll click "expand" to see more details, and from this page they'll likely contact the organization directly. 

(We've planned to also show these resources in the ContributionPage results, but for this page's purposes, we think we can assume they'll go directly to the org)

here's some sample data: https://docs.google.com/spreadsheets/d/136THS9XWHm7VifxEcQc8q_y6DgiNjht6XO_jEgaj4F0/edit

**Comment by isabeltunguxd** [comment]
Created some wireframes for community resources page: https://www.figma.com/file/gxycal4Gj9tMwkpLlvxu6w/RubyforGood-Mutual-Aid?node-id=2%3A24
