### ISSUE TITLE
Add heroku install version badges to readme 

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#672]
We have two heroku installs: `mutual-aid-demo` and `mutual-aid-test`. Would be great for our [README.md] to show badges indicating up/down status and deployed versions.

**Comment by Shaglock** [comment]
Hey @exbinary! I've added [PR](https://github.com/rubyforgood/mutual-aid/pull/768) for up/down badges. I am not sure that we can show deployed version badge, at least I didn't find any solution for that.
