### ISSUE TITLE
Build out Community Resources page

### ISSUE THREAD

**Issue by svileshina** [rubyforgood/mutual-aid#692]
https://www.figma.com/file/gxycal4Gj9tMwkpLlvxu6w/RubyforGood--Mutual-Aid?node-id=2%3A24

<img width="1258" alt="Screen Shot 2020-09-29 at 4 23 06 PM" src="https://user-images.githubusercontent.com/7607813/94611808-4577bd80-0270-11eb-97bb-fd41b5c06d71.png">

And also see an alternate mockup in #738.

**Comment by svileshina** [comment]
This can be broken up into several issues - just let us know either here or in the #mutualaid channel what you want to take on!

**Comment by exbinary** [comment]
Obsolete.
