### ISSUE TITLE
Address minor comments on #626

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#704]
#626 was merged in with a few outstanding comments, [here](https://github.com/rubyforgood/mutual-aid/pull/699#discussion_r487544087) and [here](https://github.com/rubyforgood/mutual-aid/pull/699#pullrequestreview-492506687). This issue is a placeholder to track that work.

**Comment by exbinary** [comment]
Not sure why i'm not able to assign this to you, so tagging you instead, @slaloggia.

**Comment by slaloggia** [comment]
I think I have to have interacted with the issue before you can assign, so try now!

I have an interview this afternoon that I'm preparing for, but will start working on these tomorrow.

**Comment by exbinary** [comment]
> I think I have to have interacted with the issue before you can assign, so try now!

Working now. Also noticed you hadn't actually been added as a collaborator to the project! (Maybe that's why you were forking!?). I added you so you should see an invite in email. Of course feel free to keep using your fork if you prefer.

> I have an interview this afternoon that I'm preparing for, but will start working on these tomorrow.

Good luck!!
