### ISSUE TITLE
Implement Map on Contributions Page

### ISSUE THREAD

**Issue by kevinschlabach** [rubyforgood/mutual-aid#707]
**Story**
As a community member, I want to see a map view on the contributions page, so that I have a place to eventually see contributions visualized geographically (future stories)

**How does it work now**
contributions pages can display contributions by tile or list view only

**How should it work**
A map view is presented as a 3rd option, and a base map is displayed on the page
This story focuses on showing a map as a first pass, future story #708 will render plot points onto it

==========
**Notes**

_Workflow_
- logged in user navigates to http://mutual-aid-demo.herokuapp.com/contributions
- toggles to "Map View"
- right hand area shows a map of North America

_Technical Requirements_
- Ruby for Good is already partnered with MapBox (https://www.mapbox.com/)
- map solution needs to be no-cost, Open Street Map could be a fallback.
- future stories will leverage data in listing to find lower zoom level to display on map

_Other Ruby4Good projects that used MapBox_
- [free forest](https://github.com/rubyforgood/freeforest)
- [terrastories is almost entirely map based](https://github.com/rubyforgood/terrastories)

**Comment by lucasfeijo** [comment]
We decided to go with [MapBox](mapbox.com) because it's more cost effective and offers comparable features to other free solutions.

**Comment by kevinschlabach** [comment]
From Mae in Slack -  For whoever needs MapBox credentials:
pk.eyJ1IjoibXV0dWFsLWFpZC1hcHAiLCJhIjoiY2tmZTBvd3UwMDBhbTJ4cDlic2JmMWZoaiJ9.rWscBjdl1SMT5N0yekIJYg
Lmk if an sk is needed!

**Comment by thestephenmarshall** [comment]
[contributions.pdf](https://github.com/rubyforgood/mutual-aid/files/5265352/contributions.pdf)

For pin info, try and use the card design from page 2.

**Comment by kevinschlabach** [comment]
per standup this morning, we should probably shift focus to the next story and proving out that data can be plotted on the map

**Comment by kevinschlabach** [comment]
per standup this afternoon, this has been merged... pending deploy to demo box to review and close

**Comment by kevinschlabach** [comment]
visible in demo box... not sure what the weird tile is in the middle... discuss tomorrow at standup?

<img width="1290" alt="Screen Shot 2020-09-23 at 4 18 27 PM" src="https://user-images.githubusercontent.com/44237304/94064978-76f81100-fdb8-11ea-909c-5125f21d51e2.png">

**Comment by h-m-m** [comment]
@thestephenmarshall Hi — we're looking at the PDF in this issue to help us with more work going forward, so thanks! It's proving helpful. Do you have any other updates to it not already included in the link above? @svileshina thinks you might have shown us a slightly different version at some point

**Comment by thestephenmarshall** [comment]
@h-m-m sorry, I missed this notification. All of the updates are in the link above.
