### ISSUE TITLE
Plot Contributions onto Map

### ISSUE THREAD

**Issue by kevinschlabach** [rubyforgood/mutual-aid#708]
**Story**
As a community member, I want to see contributions with locations plotted on the map view on the contributions page, so that I can consume the listing via a geospatial layout

**How does it work now**
#707 put a map on the contributions page

**How should it work**
A map view presenting listed contributions _(removed from scope: and sets zoom level to include everything on the map)_

==========
**Notes**

_Workflow_
- logged in user navigates to http://mutual-aid-demo.herokuapp.com/contributions
- toggles to "Map View"
- right hand area shows a map community area based on data contained
-- if no data can be plotted and contained, then fall back to a generic zoom level of north america

_Technical Requirements_
- N/A

**Comment by thestephenmarshall** [comment]
Mock is located [here](https://github.com/rubyforgood/mutual-aid/issues/707#issuecomment-697109318). For the map pins, use the cards from tile view.

**Comment by kevinschlabach** [comment]
This was noted on the PR for this item, but to include it here for business view eyeballs...

The delivery of this story was not able to include setting the zoom level to the locale/metro of the data.  That will need to be broken out as a separate story as it needs more data pulled into the page and we ran out of time this week.

**Comment by kevinschlabach** [comment]
this has been merged, but shouldn't be closed until it is visible in the demo environment and the prior comment is reviewed and potentially broken out as a new story...?
