### ISSUE TITLE
Initiate match via P2P email

### ISSUE THREAD

**Issue by kevinschlabach** [rubyforgood/mutual-aid#709]
**Story**
As a community member, I want to email another contributor directly, so that I don't need a dispatcher to match us up.

**How does it work now**
A dispatcher finds an offer and an ask and creates a tentative match

**How should it work**
A logged in member can view listings and email that person without exposing personal contact information
This story focuses on email as a first pass, future story #711  will consider text

==========
**Notes**

_Workflow_

1. logged in user navigates to http://mutual-aid-demo.herokuapp.com/contributions
2. clicks button "view" ("existing" respond button is for dispatchers)
3. reads details of contribution (PII information such as name, contacts are blinded)
4. confirms intent to message contribution author directly
5. enters a message to be sent to that contribution's contact
6. message is sent without either party's contact information exposed (unless sender intentionally puts it within the message, which they will selectively need to do in order to get a response)
A- if the person attempting to make the claim does NOT yet have a person record tied to their acount, then we also need to collect additional fields to create it on the fly: Name, preferred contact, data value of preferred contact  (preferred contact has to verify that contact method contains valid data, validation in person model shoud be leveraged)

_Options_
- message comes from "do not reply address" from platform
- future stretch goal: anonymized reply-to address that user could respond to and thread could continue back and forth (like Craigslist)

_Technical Requirement_
- on the contributions page, there are two possible buttons to display: Respond and View
-- respond exists today and should only appear for dispatchers, admins, and superadmins
-- view should only appear if the P2P feature toggle is on, and it would show for all users initially (might be hidden from dispatchers in the future so they don't get confused)
- all messages sent this way should be logged in the communication logs table
- the two parties should be set as a match in the database

**Comment by thestephenmarshall** [comment]
Existing wireframe: https://www.figma.com/file/gxycal4Gj9tMwkpLlvxu6w/RubyforGood--Mutual-Aid?node-id=0%3A1

**Comment by thestephenmarshall** [comment]
Here is the initial envisioned P2P flow. Some things to note:

- Contributions page will not require login (future)
- `Dispatch Required` section needs separate flow created for dispatchers

![p2p-flow1](https://user-images.githubusercontent.com/2293844/93891591-2ea1fb80-fcb1-11ea-992c-808f35b57e14.jpg)

**Comment by kevinschlabach** [comment]
updated description to match standup conversation this afternoon

**Comment by thestephenmarshall** [comment]
[p2p-design.pdf](https://github.com/rubyforgood/mutual-aid/files/5265343/p2p-design.pdf)

**Comment by kevinschlabach** [comment]
(standup) need to catch sessions where the person record is not yet created to match the account.... in that flow, catch and request these additional fields: Name, preferred contact, data value of preferred contact.... preferred contact has to verify that contact approach has valid data (validation in person model to be leveraged)

**Comment by kevinschlabach** [comment]
conversation summary in Slack:
when the recipient of the claim doesn't have an email (they might only have a phone number for text), then this flow doesn't work.  The options are to either not show the claim button on the contribution page tiles, or to pop a banner with a message when clicked.  This second one is preferred if it isn't much more expensive than the first.  Message should say "We are sorry, this contributor hasn't provided an email address yet and can't communicate this way"

Also... @exbinary confirmed/suggested the subject line for these emails could be: "<name> is offering to meet your ask" and  "<name> would like to accept your offer"
