### ISSUE TITLE
Improve Project Onboarding via Docker Config Enhancements

### ISSUE THREAD

**Issue by kevinschlabach** [rubyforgood/mutual-aid#712]
> In order to provide a smoother development experience
> We want the ability to run the `webpack-dev-server` as a parallel service in the Docker development environment
> So webpacks can be compiled out-of-band from requests to the web server.

Currently, the Docker development environment attempts to compile webpacks on the first web request - ie in-band webpack compilation. Since the compilation happens as a blocking operation on the web request, often, the webpack compilation runs up against against the rack-timeout limit and the request is killed, the asset compilation thread is also killed setting up the whole cycle to be repeated on the next web request.

What we want to do here is offer developers who are using the Docker development setup a way to run the webpacker-dev-server as a parallel process to compile the assets before the first web request, then watch for updates in order to auto-recompile packs.

**Comment by indiebrain** [comment]
Code complete via merge of https://github.com/rubyforgood/mutual-aid/pull/715
