### ISSUE TITLE
Seed Demo Environment with Location Data

### ISSUE THREAD

**Issue by kevinschlabach** [rubyforgood/mutual-aid#716]
Goal - add some placeholder data to the Demo Environment so that it's easier for new open source project contributors to gain context and play with the data.  Also, increase ability to validate/test the map feature being tackled in #707 and #708 

Using the UI, I created the following structure for service areas 
_(see attached for reference images to aid those not familiar with the Philadelphia metro)_

**Pod** 

- University - Temple (Philadelphia, PA 19122) - Philadelphia, , Lower North
- University - Drexel (Philadelphia, PA 19104) - Philadelphia, , West
- University - Penn (Philadelphia, PA 19104) - Philadelphia, , West

**Neighborhood**

- Center City (Philadelphia, PA 19107) - Philadelphia,  , Center City
- South (Philadelphia, PA 19112) - Philadelphia,  , South
- Southwest (Philadelphia, PA 19142) - Philadelphia,  , Southwest
- West (Philadelphia, PA 19139) - Philadelphia,  , West
- Lower North (Philadelphia, PA 19123) - Philadelphia,  , Lower North
- Upper North (Philadelphia, PA 19133) - Philadelphia,  , Upper North
- Kensington (Philadelphia, PA 19134) - Philadelphia,  , Kensington
- Lower Northeast (Philadelphia, PA 19149) - Philadelphia,  , Lower Northeast
- Upper Northeast (Philadelphia, PA 19154) - Philadelphia,  , Upper Northeast
- Olney (Philadelphia, PA 19126) - Philadelphia,  , Olney
- Germantown (Philadelphia, PA 19119) - Philadelphia,  , Germantown
- Roxborough (Philadelphia, PA 19128) - Philadelphia,  , Roxborough
- Chester (Chester, PA 19103) - Chester

**Region**

 - none

**County**

- Philadelphia City (Philadelphia, PA 19107) - Philadelphia  _<< all neighborhoods point here, except Chester_
- Suburbs - Northern (Langhorne, PA 19047) - Bucks
- Suburbs - Southern  (Chester, PA 19103) - Delaware
- Suburbs - Eastern / NJ (Camden, NJ 08103) - Camden
- Suburbs - Western (Wayne, PA 19087) - Montgomery

**City**

 - Larger Philadelphia Metro (Philadelphia PA 19107) _<< all counties point here_

**Other**

- none

Items listeed above are in this field order (in case someone wants to make a DB script)
- Name (City, ST, Zip) - County, Region, Neighborhood

**Philadelphia neighborhood and zip code map**

<img width="475" alt="philadelphia-neighbordhoods-zips" src="https://user-images.githubusercontent.com/44237304/93925653-70986500-fce4-11ea-982a-ccbc9b578b85.png">

**Surrounding county map:**

<img width="731" alt="philadelphia-counties-nearby" src="https://user-images.githubusercontent.com/44237304/93925682-7c842700-fce4-11ea-9e9a-d8ecbeeef1ec.png">

**Comment by kevinschlabach** [comment]
I opened bug #727 while working on this... it seems some items don't show in filters unless all filters are on.

**Comment by kevinschlabach** [comment]
I went through all the contributions and provided offer/ask content to make the system feel more realistic... I think I've done enough here to move the ball forward.  Would like one of the leaders to review and comment or move this to done.

**Comment by kevinschlabach** [comment]
@exbinary wants to get a db snapshot before we close... makes sense!

**Comment by exbinary** [comment]
This is amazing content @kevinschlabach , thank you! 🙌🏾🔥
I've taken a db snapshot on [heroku](https://data.heroku.com/datastores/17c4cafe-3c24-41fb-8c39-769ff9620154#durability) (9/24). Done and done!
