### ISSUE TITLE
User is able to select filters quickly

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#756]
Right now you have to select each individual check box. It would be great to be able to check all/uncheck all by column as well as the entire filters section

<img width="1167" alt="Screen Shot 2020-09-29 at 3 10 45 PM" src="https://user-images.githubusercontent.com/7607813/94604649-faf14380-0265-11eb-81eb-a8e79a8592bd.png">

**Comment by Shaglock** [comment]
Hello guys! I've [added PR](https://github.com/rubyforgood/mutual-aid/pull/799) for this issue.

**Comment by Shaglock** [comment]
Hey guys! Any news about this issue? Could you please take a look at PR that I created a month ago?
