### ISSUE TITLE
Delete all pending rspec examples that were autogenerated

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#763]
Most of our pending specs were generated through scaffolding and can be removed. They'll have to be compared against a default scaffolded example to ensure we're not removing anything that actually has had any work put into it.

This will help us narrow in on the actual pending specs that need to be re-instated.

**Comment by Llambi** [comment]
I'd like to work on this 🎉

**Comment by fabiosoaresv** [comment]
@exbinary I was looking for issues to work on for Hacktoberfest and I would to pick this up if possible. Thanks!

**Comment by exbinary** [comment]
Apologies @fabiosoaresv. This had already been address in #766.
Appreciate your interest, and please lmk if we can help you identify a different issue to work on.
