### ISSUE TITLE
show_navbar option should toggle display on /community_resources and /announcements

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#770]
This boolean should only affect:
* community resources
* announcements pages
* asks|offers
* respective confirmation pages for all the above

Whereas right now it seems to affect all (?) pages?

**Comment by gamecat2d** [comment]
Hi, sorry for my english it is not my mother tongue !

I think i found the problem, determine_layout (to hide/show the navbar) is in the controller of community ressources, announcements but in the public pages controller too. It concerns pages like the landing page, about page, version page and maybe contribution soon (?).

Is navbar always shown on the about page, etc ?
If i remove this determine_layout in the public controller and set the display boolean to false, the navbar is always visible except when adding a community ressource or an announcement for example.

Best regards and stay safe !

**Comment by exbinary** [comment]
I believe this was fixed in #966.
