### ISSUE TITLE
Upgrade to ruby 2.7.2

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#782]

**Comment by kinduff** [comment]
Happy to claim!

**Comment by akp2603** [comment]
@exbinary is this issue still available? If yes, can you assign it to me?

**Comment by exbinary** [comment]
Hi @akp2603 , appreciate your interest 👋🏾.
I see that @kinduff also expressed interest a couple of days ago.

We'd be happy for either of you to take it; maybe let's give @kinduff a couple days to weigh in, in case they've already started work on it?

Thanks both!

**Comment by kinduff** [comment]
@exbinary @akp2603 Hey! Working on this, publishing a PR in short

**Comment by exbinary** [comment]
Thanks @kinduff ! 🙏🏾

**Comment by sharvy** [comment]
@kinduff Looks like this issue is still open. Do you mind if I take it over?

cc: @exbinary

**Comment by kinduff** [comment]
Please go ahead @sharvy! Lost track of time
