### ISSUE TITLE
Make our glossary publicly accessible

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#783]
It currently lives at http://mutual-aid-demo.herokuapp.com/admin/glossary which requires login.
We'd like to make it accessible without having to login.

**Comment by exbinary** [comment]
> I can't see the glossary, it asks me to login.

Hello @UntouchedOdin0! 👋🏾.

Yes, currently the glossary requires login, and i see how the title of this issue was not clear. I've changed it to make it clearer that we'd like to open it up for anyone to be able to view it.

Thanks!

**Comment by fridaland** [comment]
I'll take this one. :)

**Comment by maebeale** [comment]
great, @fridaland !
