### ISSUE TITLE
Developers are able to easily modify our glossary

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#784]
Currently, changes to the glossary require code changes, commit and PR. Ideally, developers who don't have the dev environment setup (eg designers, PMs, etc) could edit the glossary as well.

Perhaps the glossary page on the app could embed a google document? Or similar solution?

**Comment by janessatran** [comment]
Hi! I'm interested in working on this issue and had a few questions about what modifications we'd like to enable. Here are some of the modifications I was thinking of:

- As a logged in user, I'd like to be able to add a new item to the list.
- As a logged in user, I'd like to be able to edit an existing item on the list (including the name, url, and description).
- As a logged in user, I'd like to be able to remove an item from the list. 

Am I missing anything or including anything I shouldn't? Thanks in advance!

**Comment by maebeale** [comment]
@janessatran hey there! Psyched you're interested in this ticket. You've got it! I think the first pass should assume all strings, but perhaps a follow-up ticket could be to add a wysiwyg and/or to allow raw html for bullets, etc. The system settings fields is our closest model where we store, sanitize and then render html.

**Comment by exbinary** [comment]
Fixed in #808
