### ISSUE TITLE
Introduce a rubocop 'todo list'

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#796]
Give Developers a clean baseline for new code and allow for existing offenses to be cleaned up over time. See rubocop [auto-generated config](https://docs.rubocop.org/rubocop/1.0/configuration.html#automatically-generated-configuration) docs.

**Comment by smoline** [comment]
@exbinary Please assign this one to me.

**Comment by exbinary** [comment]
Fixed in #800 and #935.
