### ISSUE TITLE
Menu bar not displaying correctly on public contribution forms when the admin option says to

### ISSUE THREAD

**Issue by h-m-m** [rubyforgood/mutual-aid#806]
### Steps to recreate:

- Go to https://mutual-aid-nwmi.herokuapp.com/offers/new https://mutual-aid-nwmi.herokuapp.com/asks/new

additionally, if you have admin access

- Go to the admin settings page (`/system_settings/1/edit?locale=en`) and verify the "display nav bar" setting is on

### Expected results

The nav bar / menu shows up on the form page URLs above

### Observed results

The nav bar is not shown on those pages

**Comment by gamecat2d** [comment]
i give it a try !

**Comment by exbinary** [comment]
I believe this was fixed in #966.
