### ISSUE TITLE
Clicking Cancel on the New Community Resource page asks for login

### ISSUE THREAD

**Issue by svileshina** [rubyforgood/mutual-aid#825]
When creating a community resource while not logged in, if you click Cancel you are taken to the login page and the "you need to be logged in alert comes up" which makes it appear as if something has gone wrong. 

Option for solution: 
Possibly pending Pundit PR - community resources index could be public so that all users (or at least non admin users) are redirected there after they press either cancel or create.

<img width="1248" alt="Screen Shot 2021-01-18 at 5 37 06 PM" src="https://user-images.githubusercontent.com/7723308/104968939-41091900-59b5-11eb-8b72-47c802ece58e.png">

**Comment by exbinary** [comment]
No longer an issue.
