### ISSUE TITLE
Prevent p2p user from claiming a contribution that does not have an email.

### ISSUE THREAD

**Issue by exbinary** [rubyforgood/mutual-aid#831]

**Comment by h-m-m** [comment]
We have discussed changing this so that the ask & offer forms will require emails if you're in p2p mode. This change should be enough to work around the fact that email is currently the only thing we support for logged out users

**Comment by exbinary** [comment]
> We have discussed changing this so that the ask & offer forms will require emails if you're in p2p mode. This change should be enough to work around the fact that email is currently the only thing we support for logged out users

... and then after further discussion, we returned to the original idea of solving this on the claiming end instead.

We tossed around different possible solutions but landed on the idea that a future 'hybrid' mode might have to solve for this problem anyway -- where contributions w/ email can be claimed but those w/o email can be dispatched. In that world, solving this in the claim flow or on /contributions felt more appropriate.
