### ISSUE TITLE
Change CommunityResources index to be grouped by Service Area and then Category

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#865]
Users would like to view CommunityResources page grouped, with headings for ServiceArea and then by Category

(later would love a toggle to be able to swap that nesting and view grouped first by Category and then by Service Area)

**Comment by exbinary** [comment]
I'd love to learn what folks are wanting to accomplish with this grouping. Could filters (similar to what we have on /contributions) serve the same purpose?
