### ISSUE TITLE
Change button text on Claim page for Ask

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#871]
Instead of "Claim this ask", button text could be "Help this person"
(keep "Claim this offer" text as is)

**Comment by 96RadhikaJadhav** [comment]
@maebeale  Can I work on the issue?

**Comment by Stearnzy** [comment]
@maebeale I see this issue is still up.  I'm currently downloading the repo, may I work on it if it's still available?

**Comment by exbinary** [comment]
Fixed in #988.
