### ISSUE TITLE
Revisit CommunityResources index and their 'inexhaustibility'.

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#882]

**Comment by exbinary** [comment]
Addressed in #980 .

**Comment by exbinary** [comment]
Mistakenly closed above. There's more work needed on this:
* Community Resources are now shown on `/contributions` but `/community_resources` still exists as a flat, unfilterable view. We should consider removing the latter or guiding users from there to the former.
* Need to revisit 'inexhaustibility' and how this is presented on `/contributions`.
