### ISSUE TITLE
Update Announcement Show to be more palatable to the public

### ISSUE THREAD

**Issue by maebeale** [rubyforgood/mutual-aid#885]
* Remove the label/data format
* Make title be the header (instead of Show Announcement)
* Display Description (or "(no description)")
* Remove date range and instead add note re when it will expire

**Comment by hairedfox** [comment]
@maebeale I'd love to take this issue. Thank you

**Comment by hairedfox** [comment]
@maebeale 
> Remove the label/data format
Does this mean that you want to remove all the labels?

> Make title be the header (instead of Show Announcement)
Is it `annoucement.name`? 

> Remove date range and instead add note re when it will expire
Could you explain more about this line? Thank you

**Comment by exbinary** [comment]
I believe this was addressed in #928 .
