### ISSUE TITLE
Create Announcement with all fields inputted but name and description are nil

### ISSUE THREAD

**Issue by hairedfox** [rubyforgood/mutual-aid#924]
I've just tried the app for the first time and looking for issues to contribute.

When I first started the app, because there's no seed data of Announcement so I tried to create a record.

<img width="715" alt="Screen Shot 2021-04-04 at 3 16 57 AM" src="https://user-images.githubusercontent.com/42526152/113490488-758c6b80-94f4-11eb-9d91-069403debe9e.png">

When checking in the rails console, I saw the `name` and `description` are nil now, but the `publish_from` and `publish_until` are correct.
![Screen Shot 2021-04-04 at 3 17 18 AM](https://user-images.githubusercontent.com/42526152/113490530-da47c600-94f4-11eb-975d-1bc3bb194b6e.png)

# Expected
- Create Announcement successfully with all input fields

**Comment by maebeale** [comment]
Hello! I believe these values are stored in the string_translations table
bc of the mobility gem. When you go to the home page, do you see the
announcement displayed?

**Comment by hairedfox** [comment]
@maebeale I do after approving the announcement. I've never used the Mobility gem before so it's a little weird when looking at the console like this and can still retrieve the attribute 😅 

I confirmed that it's completely normal. Thank you for pointing it out. :bow:

**Comment by maebeale** [comment]
If you add `.i18n`, it'll pull the "translations"
